//
//  This CSharp output file generated by Gardens Point LEX
//  Version:  1.2.0
//  Machine:  VIRGILP-MACW7
//  DateTime: 10/19/2012 11:18:41 AM
//  UserName: virgilp
//  GPLEX input file <NLiquidScaner.lex - 10/19/2012 11:17:17 AM>
//  GPLEX frame file <embedded resource>
//
//  Option settings: unicode, verbose, parser, stack, minimize
//  Option settings: classes, compressMap, compressNext, persistBuffer, embedbuffers
//  Fallback code page: Target machine default
//

//
// Experimental embedded frame
// Version 1.1.4 of 10-May-2010
//
//
#define BACKUP
#define STACK
#define PERSIST

using System;
using System.IO;
using System.Text;
using System.Globalization;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Diagnostics.CodeAnalysis;

using NLiquid.Runtime;

namespace NLiquid.Analyzing
{   
    /// <summary>
    /// Summary Canonical example of GPLEX automaton
    /// </summary>
    
#if STANDALONE
    //
    // These are the dummy declarations for stand-alone GPLEX applications
    // normally these declarations would come from the parser.
    // If you declare /noparser, or %option noparser then you get this.
    //

     public enum Tokens
    { 
      EOF = 0, maxParseToken = int.MaxValue 
      // must have at least these two, values are almost arbitrary
    }

     public abstract class ScanBase
    {
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public abstract int yylex();

        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yywrap")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yywrap")]
        protected virtual bool yywrap() { return true; }

#if BABEL
        protected abstract int CurrentSc { get; set; }
        // EolState is the 32-bit of state data persisted at 
        // the end of each line for Visual Studio colorization.  
        // The default is to return CurrentSc.  You must override
        // this if you want more complicated behavior.
        public virtual int EolState { 
            get { return CurrentSc; }
            set { CurrentSc = value; } 
        }
    }
    
     public interface IColorScan
    {
        void SetSource(string source, int offset);
        int GetNext(ref int state, out int start, out int end);
#endif // BABEL
    }

#endif // STANDALONE
    
    // If the compiler can't find the scanner base class maybe you
    // need to run GPPG with the /gplex option, or GPLEX with /noparser
#if BABEL
     public sealed partial class Scanner : ScanBase, IColorScan
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
        
        protected override int CurrentSc 
        {
             // The current start state is a property
             // to try to avoid the user error of setting
             // scState but forgetting to update the FSA
             // start state "currentStart"
             //
             get { return currentScOrd; }  // i.e. return YY_START;
             set { currentScOrd = value;   // i.e. BEGIN(value);
                   currentStart = startState[value]; }
        }
#else  // BABEL
     public sealed partial class Scanner : ScanBase
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
#endif // BABEL
        
        /// <summary>
        /// The input buffer for this scanner.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ScanBuff Buffer { get { return buffer; } }
        
        private static int GetMaxParseToken() {
     System.Reflection.FieldInfo f = typeof(Tokens).GetField("maxParseToken");
            return (f == null ? int.MaxValue : (int)f.GetValue(null));
        }
        
        static int parserMax = GetMaxParseToken();
        
        enum Result {accept, noMatch, contextFound};

        const int maxAccept = 167;
        const int initial = 1;
        const int eofNum = 0;
        const int goStart = -1;
        const int INITIAL = 0;
        const int CMMT = 1;
        const int CMMT2 = 2;
        const int CMMT3 = 3;
        const int RAW = 4;
        const int RAW2 = 5;
        const int RAW3 = 6;
        const int INTAG = 7;
        const int INOUTPUT = 8;

#region user code
public override void yyerror(string format, params object[] args) 
{
	System.Console.Error.WriteLine("Error: line {0} - " + format, yyline);
}
#endregion user code

        int state;
        int currentStart = startState[0];
        int code;      // last code read
        int cCol;      // column number of code
        int lNum;      // current line number
        //
        // The following instance variables are used, among other
        // things, for constructing the yylloc location objects.
        //
        int tokPos;        // buffer position at start of token
        int tokCol;        // zero-based column number at start of token
        int tokLin;        // line number at start of token
        int tokEPos;       // buffer position at end of token
        int tokECol;       // column number at end of token
        int tokELin;       // line number at end of token
        string tokTxt;     // lazily constructed text of token
#if STACK          
        private Stack<int> scStack = new Stack<int>();
#endif // STACK

#region ScannerTables
    struct Table {
        public int min; public int rng; public int dflt;
        public short[] nxt;
        public Table(int m, int x, int d, short[] n) {
            min = m; rng = x; dflt = d; nxt = n;
        }
    };

    static int[] startState = new int[] {1, 6, 172, 182, 183, 14, 
        18, 192, 198, 0};

#region CompressedCharacterMap
    //
    // There are 39 equivalence classes
    // There are 2 character sequence regions
    // There are 1 tables, 126 entries
    // There are 1 runs, 0 singletons
    // Decision tree depth is 1
    //
    static sbyte[] mapC0 = new sbyte[126] {
/*     '\0' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 2, 4, 2, 2, 
/*   '\x10' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/*   '\x20' */ 4, 33, 9, 2, 2, 1, 2, 10, 37, 38, 2, 2, 7, 2, 8, 2, 
/*      '0' */ 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 6, 2, 36, 34, 35, 2, 
/*      '@' */ 2, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 
/*      'P' */ 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 2, 2, 2, 2, 19, 
/*      '`' */ 2, 16, 29, 21, 26, 14, 15, 32, 31, 28, 19, 19, 17, 23, 24, 22, 
/*      'p' */ 25, 19, 12, 18, 11, 13, 19, 27, 19, 30, 19, 0, 5, 3 };

    static sbyte MapC(int code)
    { // '\0' <= code <= '\U0010FFFF'
      if (code < 126) // '\0' <= code <= '}'
        return mapC0[code - 0];
      else // '~' <= code <= '\U0010FFFF'
        return (sbyte)2;
    }
#endregion

    static Table[] NxS = new Table[203] {
/* NxS[   0] */ new Table(0, 0, 0, null), // Shortest string ""
/* NxS[   1] */ // Shortest string ""
      new Table(0, 1, 2, new short[] {168}),
/* NxS[   2] */ // Shortest string "%"
      new Table(0, 1, 2, new short[] {169}),
/* NxS[   3] */ // Shortest string ""
      new Table(0, 2, 3, new short[] {169, -1}),
/* NxS[   4] */ new Table(0, 0, -1, null), // Shortest string ""
/* NxS[   5] */ new Table(0, 0, -1, null), // Shortest string ""
/* NxS[   6] */ // Shortest string ""
      new Table(0, 1, 7, new short[] {170}),
/* NxS[   7] */ // Shortest string "%"
      new Table(0, 1, 7, new short[] {171}),
/* NxS[   8] */ // Shortest string ""
      new Table(1, 1, 8, new short[] {-1}),
/* NxS[   9] */ new Table(0, 0, -1, null), // Shortest string ""
/* NxS[  10] */ // Shortest string "\t"
      new Table(4, 1, -1, new short[] {10}),
/* NxS[  11] */ new Table(0, 0, -1, null), // Shortest string "endcomment"
/* NxS[  12] */ // Shortest string "\t"
      new Table(4, 1, -1, new short[] {12}),
/* NxS[  13] */ new Table(0, 0, -1, null), // Shortest string "%}"
/* NxS[  14] */ // Shortest string ""
      new Table(0, 1, 15, new short[] {185}),
/* NxS[  15] */ // Shortest string "%"
      new Table(0, 1, 15, new short[] {186}),
/* NxS[  16] */ // Shortest string ""
      new Table(1, 1, 16, new short[] {-1}),
/* NxS[  17] */ new Table(0, 0, -1, null), // Shortest string ""
/* NxS[  18] */ // Shortest string ""
      new Table(4, 11, -1, new short[] {18, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, 187}),
/* NxS[  19] */ new Table(0, 0, -1, null), // Shortest string "endraw"
/* NxS[  20] */ // Shortest string "\t"
      new Table(4, 1, -1, new short[] {20}),
/* NxS[  21] */ new Table(0, 0, -1, null), // Shortest string ":"
/* NxS[  22] */ new Table(0, 0, -1, null), // Shortest string ","
/* NxS[  23] */ // Shortest string "."
      new Table(8, 1, -1, new short[] {149}),
/* NxS[  24] */ // Shortest string "t"
      new Table(11, 22, -1, new short[] {30, 134, 30, 30, 30, 135, 
          30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 136, 30, 30, 30, 30}),
/* NxS[  25] */ // Shortest string "r"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 132, 
          30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  26] */ // Shortest string "u"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 30, 30, 30, 127, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  27] */ // Shortest string "e"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          94, 30, 30, 30, 30, 30, 30, 95, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  28] */ // Shortest string "f"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 88, 
          30, 30, 30, 30, 30, 89, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  29] */ // Shortest string "a"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 81, 30, 30, 30, 30, 30, 82, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  30] */ // Shortest string "l"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  31] */ // Shortest string "0"
      new Table(8, 13, -1, new short[] {197, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, 31}),
/* NxS[  32] */ // Shortest string "c"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 62, 
          30, 30, 30, 30, 30, 63, 30, 30, 30, 30, 30, 30, 30, 64, 30, 30}),
/* NxS[  33] */ // Shortest string "o"
      new Table(33, 19, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 61}),
/* NxS[  34] */ // Shortest string "n"
      new Table(28, 22, 30, new short[] {59, 30, 30, 30, 30, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  35] */ // Shortest string "w"
      new Table(28, 22, 30, new short[] {53, 30, 30, 54, 30, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  36] */ // Shortest string "i"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 46, 30, 
          30, 30, 30, 30, 30, 30, 30, 47, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  37] */ // Shortest string "="
      new Table(34, 1, -1, new short[] {44}),
/* NxS[  38] */ // Shortest string ">"
      new Table(34, 1, -1, new short[] {43}),
/* NxS[  39] */ // Shortest string "<"
      new Table(34, 1, -1, new short[] {42}),
/* NxS[  40] */ new Table(0, 0, -1, null), // Shortest string "("
/* NxS[  41] */ new Table(0, 0, -1, null), // Shortest string ")"
/* NxS[  42] */ new Table(0, 0, -1, null), // Shortest string "<="
/* NxS[  43] */ new Table(0, 0, -1, null), // Shortest string ">="
/* NxS[  44] */ new Table(0, 0, -1, null), // Shortest string "=="
/* NxS[  45] */ new Table(0, 0, -1, null), // Shortest string "!="
/* NxS[  46] */ // Shortest string "if"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  47] */ // Shortest string "in"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 48, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  48] */ // Shortest string "inc"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          49, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  49] */ // Shortest string "incl"
      new Table(33, 20, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 50}),
/* NxS[  50] */ // Shortest string "inclu"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 30, 30, 30, 30, 30, 51, 30, 30, 30, 30, 30, 30}),
/* NxS[  51] */ // Shortest string "includ"
      new Table(33, 21, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 30, 52}),
/* NxS[  52] */ // Shortest string "include"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  53] */ // Shortest string "wi"
      new Table(33, 18, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 57}),
/* NxS[  54] */ // Shortest string "wh"
      new Table(33, 21, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 30, 55}),
/* NxS[  55] */ // Shortest string "whe"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 30, 30, 30, 56, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  56] */ // Shortest string "when"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  57] */ // Shortest string "wit"
      new Table(31, 19, 30, new short[] {58, 30, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  58] */ // Shortest string "with"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  59] */ // Shortest string "ni"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          60, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  60] */ // Shortest string "nil"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  61] */ // Shortest string "or"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  62] */ // Shortest string "ca"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 73, 30, 30, 30, 30, 30, 30, 74, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  63] */ // Shortest string "co"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 30, 30, 68, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  64] */ // Shortest string "cy"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 65, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  65] */ // Shortest string "cyc"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          66, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  66] */ // Shortest string "cycl"
      new Table(33, 21, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 30, 67}),
/* NxS[  67] */ // Shortest string "cycle"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  68] */ // Shortest string "com"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 30, 30, 69, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  69] */ // Shortest string "comm"
      new Table(33, 21, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 30, 70}),
/* NxS[  70] */ // Shortest string "comme"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 30, 30, 30, 71, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  71] */ // Shortest string "commen"
      new Table(33, 18, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 72}),
/* NxS[  72] */ // Shortest string "comment"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  73] */ // Shortest string "cas"
      new Table(33, 21, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 30, 79}),
/* NxS[  74] */ // Shortest string "cap"
      new Table(33, 18, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 75}),
/* NxS[  75] */ // Shortest string "capt"
      new Table(33, 20, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 76}),
/* NxS[  76] */ // Shortest string "captu"
      new Table(33, 19, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 77}),
/* NxS[  77] */ // Shortest string "captur"
      new Table(33, 21, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 30, 78}),
/* NxS[  78] */ // Shortest string "capture"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  79] */ // Shortest string "case"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  80] */ // Shortest string "0.0"
      new Table(20, 1, -1, new short[] {80}),
/* NxS[  81] */ // Shortest string "as"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 84, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  82] */ // Shortest string "an"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 30, 30, 30, 30, 30, 83, 30, 30, 30, 30, 30, 30}),
/* NxS[  83] */ // Shortest string "and"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  84] */ // Shortest string "ass"
      new Table(28, 22, 30, new short[] {85, 30, 30, 30, 30, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  85] */ // Shortest string "assi"
      new Table(32, 18, 30, new short[] {86, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  86] */ // Shortest string "assig"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 30, 30, 30, 87, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  87] */ // Shortest string "assign"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  88] */ // Shortest string "fa"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          91, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  89] */ // Shortest string "fo"
      new Table(33, 19, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 90}),
/* NxS[  90] */ // Shortest string "for"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  91] */ // Shortest string "fal"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 92, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  92] */ // Shortest string "tru"
      new Table(33, 21, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 30, 93}),
/* NxS[  93] */ // Shortest string "true"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  94] */ // Shortest string "el"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 125, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  95] */ // Shortest string "en"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 30, 30, 30, 30, 30, 96, 30, 30, 30, 30, 30, 30}),
/* NxS[  96] */ // Shortest string "end"
      new Table(11, 22, -1, new short[] {97, 30, 98, 30, 99, 30, 
          30, 30, 30, 30, 100, 30, 30, 30, 30, 30, 30, 101, 30, 30, 30, 30}),
/* NxS[  97] */ // Shortest string "endt"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 118, 
          30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  98] */ // Shortest string "endu"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 30, 30, 30, 113, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[  99] */ // Shortest string "endf"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 30, 111, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[ 100] */ // Shortest string "endc"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 103, 
          30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[ 101] */ // Shortest string "endi"
      new Table(33, 22, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 30, 30, 102}),
/* NxS[ 102] */ // Shortest string "endif"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[ 103] */ // Shortest string "endca"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 104, 30, 30, 30, 30, 30, 30, 105, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[ 104] */ // Shortest string "endcas"
      new Table(33, 21, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 30, 110}),
/* NxS[ 105] */ // Shortest string "endcap"
      new Table(33, 18, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 106}),
/* NxS[ 106] */ // Shortest string "endcapt"
      new Table(33, 20, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 107}),
/* NxS[ 107] */ // Shortest string "endcaptu"
      new Table(33, 19, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 108}),
/* NxS[ 108] */ // Shortest string "endcaptur"
      new Table(33, 21, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 30, 109}),
/* NxS[ 109] */ // Shortest string "endcapture"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[ 110] */ // Shortest string "endcase"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[ 111] */ // Shortest string "endfo"
      new Table(33, 19, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 112}),
/* NxS[ 112] */ // Shortest string "endfor"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[ 113] */ // Shortest string "endun"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          114, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[ 114] */ // Shortest string "endunl"
      new Table(33, 21, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 30, 115}),
/* NxS[ 115] */ // Shortest string "endunle"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 116, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[ 116] */ // Shortest string "endunles"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 117, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[ 117] */ // Shortest string "endunless"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[ 118] */ // Shortest string "endta"
      new Table(29, 21, 30, new short[] {119, 30, 30, 30, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[ 119] */ // Shortest string "endtab"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          120, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[ 120] */ // Shortest string "endtabl"
      new Table(33, 21, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 30, 121}),
/* NxS[ 121] */ // Shortest string "endtable"
      new Table(33, 19, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 122}),
/* NxS[ 122] */ // Shortest string "endtabler"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 30, 123, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[ 123] */ // Shortest string "endtablero"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 124, 30, 30, 30, 30, 30}),
/* NxS[ 124] */ // Shortest string "endtablerow"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[ 125] */ // Shortest string "els"
      new Table(33, 21, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 30, 126}),
/* NxS[ 126] */ // Shortest string "else"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[ 127] */ // Shortest string "un"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          128, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[ 128] */ // Shortest string "unl"
      new Table(33, 21, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 30, 129}),
/* NxS[ 129] */ // Shortest string "unle"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 130, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[ 130] */ // Shortest string "unles"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 131, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[ 131] */ // Shortest string "unless"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[ 132] */ // Shortest string "ra"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 133, 30, 30, 30, 30, 30}),
/* NxS[ 133] */ // Shortest string "raw"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[ 134] */ // Shortest string "tr"
      new Table(33, 20, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 92}),
/* NxS[ 135] */ // Shortest string "ta"
      new Table(29, 21, 30, new short[] {142, 30, 30, 30, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[ 136] */ // Shortest string "ti"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 30, 30, 137, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[ 137] */ // Shortest string "tim"
      new Table(33, 21, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 30, 138}),
/* NxS[ 138] */ // Shortest string "time"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 30, 139, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[ 139] */ // Shortest string "timeo"
      new Table(33, 20, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 140}),
/* NxS[ 140] */ // Shortest string "timeou"
      new Table(33, 18, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 141}),
/* NxS[ 141] */ // Shortest string "timeout"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[ 142] */ // Shortest string "tab"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          143, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[ 143] */ // Shortest string "tabl"
      new Table(33, 21, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 30, 144}),
/* NxS[ 144] */ // Shortest string "table"
      new Table(33, 19, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30, 145}),
/* NxS[ 145] */ // Shortest string "tabler"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 30, 146, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}),
/* NxS[ 146] */ // Shortest string "tablero"
      new Table(11, 22, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 147, 30, 30, 30, 30, 30}),
/* NxS[ 147] */ // Shortest string "tablerow"
      new Table(33, 17, 30, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[ 148] */ new Table(0, 0, -1, null), // Shortest string "\"\""
/* NxS[ 149] */ new Table(0, 0, -1, null), // Shortest string ".."
/* NxS[ 150] */ new Table(0, 0, -1, null), // Shortest string "%}"
/* NxS[ 151] */ // Shortest string "\t"
      new Table(4, 1, -1, new short[] {151}),
/* NxS[ 152] */ new Table(0, 0, -1, null), // Shortest string "|"
/* NxS[ 153] */ new Table(0, 0, -1, null), // Shortest string ":"
/* NxS[ 154] */ new Table(0, 0, -1, null), // Shortest string ","
/* NxS[ 155] */ new Table(0, 0, -1, null), // Shortest string "."
/* NxS[ 156] */ // Shortest string "t"
      new Table(33, 19, 157, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 157, 165}),
/* NxS[ 157] */ // Shortest string "r"
      new Table(33, 17, 157, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[ 158] */ // Shortest string "f"
      new Table(11, 22, -1, new short[] {157, 157, 157, 157, 157, 161, 
          157, 157, 157, 157, 157, 157, 157, 157, 157, 157, 157, 157, 157, 157, 157, 157}),
/* NxS[ 159] */ // Shortest string "0"
      new Table(8, 13, -1, new short[] {202, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, 159}),
/* NxS[ 160] */ // Shortest string "0.0"
      new Table(20, 1, -1, new short[] {160}),
/* NxS[ 161] */ // Shortest string "fa"
      new Table(11, 22, -1, new short[] {157, 157, 157, 157, 157, 157, 
          162, 157, 157, 157, 157, 157, 157, 157, 157, 157, 157, 157, 157, 157, 157, 157}),
/* NxS[ 162] */ // Shortest string "fal"
      new Table(11, 22, -1, new short[] {157, 157, 157, 157, 157, 157, 
          157, 163, 157, 157, 157, 157, 157, 157, 157, 157, 157, 157, 157, 157, 157, 157}),
/* NxS[ 163] */ // Shortest string "tru"
      new Table(33, 21, 157, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 157, 157, 157, 164}),
/* NxS[ 164] */ // Shortest string "true"
      new Table(33, 17, 157, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[ 165] */ // Shortest string "tr"
      new Table(33, 20, 157, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 157, 157, 163}),
/* NxS[ 166] */ new Table(0, 0, -1, null), // Shortest string "\"\""
/* NxS[ 167] */ new Table(0, 0, -1, null), // Shortest string "}}"
/* NxS[ 168] */ // Shortest string ""
      new Table(0, 2, 3, new short[] {4, 5}),
/* NxS[ 169] */ // Shortest string ""
      new Table(0, 2, 3, new short[] {-1, -1}),
/* NxS[ 170] */ // Shortest string ""
      new Table(1, 1, 8, new short[] {9}),
/* NxS[ 171] */ // Shortest string ""
      new Table(1, 1, 8, new short[] {-1}),
/* NxS[ 172] */ // Shortest string ""
      new Table(4, 11, -1, new short[] {10, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, 173}),
/* NxS[ 173] */ // Shortest string "e"
      new Table(24, 1, -1, new short[] {174}),
/* NxS[ 174] */ // Shortest string "en"
      new Table(26, 1, -1, new short[] {175}),
/* NxS[ 175] */ // Shortest string "end"
      new Table(21, 1, -1, new short[] {176}),
/* NxS[ 176] */ // Shortest string "endc"
      new Table(22, 1, -1, new short[] {177}),
/* NxS[ 177] */ // Shortest string "endco"
      new Table(23, 1, -1, new short[] {178}),
/* NxS[ 178] */ // Shortest string "endcom"
      new Table(23, 1, -1, new short[] {179}),
/* NxS[ 179] */ // Shortest string "endcomm"
      new Table(14, 1, -1, new short[] {180}),
/* NxS[ 180] */ // Shortest string "endcomme"
      new Table(24, 1, -1, new short[] {181}),
/* NxS[ 181] */ // Shortest string "endcommen"
      new Table(11, 1, -1, new short[] {11}),
/* NxS[ 182] */ new Table(0, 0, -1, null), // Shortest string ""
/* NxS[ 183] */ // Shortest string ""
      new Table(1, 4, -1, new short[] {184, -1, -1, 12}),
/* NxS[ 184] */ // Shortest string "%"
      new Table(3, 1, -1, new short[] {13}),
/* NxS[ 185] */ // Shortest string ""
      new Table(1, 1, 16, new short[] {17}),
/* NxS[ 186] */ // Shortest string ""
      new Table(1, 1, 16, new short[] {-1}),
/* NxS[ 187] */ // Shortest string "e"
      new Table(24, 1, -1, new short[] {188}),
/* NxS[ 188] */ // Shortest string "en"
      new Table(26, 1, -1, new short[] {189}),
/* NxS[ 189] */ // Shortest string "end"
      new Table(12, 1, -1, new short[] {190}),
/* NxS[ 190] */ // Shortest string "endr"
      new Table(16, 1, -1, new short[] {191}),
/* NxS[ 191] */ // Shortest string "endra"
      new Table(27, 1, -1, new short[] {19}),
/* NxS[ 192] */ // Shortest string ""
      new Table(33, 35, 30, new short[] {196, 37, 38, 39, 40, 41, 
          -1, 193, -1, -1, 20, -1, 21, 22, 23, 194, 195, 24, 25, 26, 27, 28, 
          29, 30, 30, 30, 31, 32, 33, 30, 34, 30, 30, 35, 36}),
/* NxS[ 193] */ // Shortest string "%"
      new Table(3, 1, -1, new short[] {150}),
/* NxS[ 194] */ // Shortest string "\""
      new Table(9, 1, 194, new short[] {148}),
/* NxS[ 195] */ // Shortest string "'"
      new Table(10, 1, 195, new short[] {148}),
/* NxS[ 196] */ // Shortest string "!"
      new Table(34, 1, -1, new short[] {45}),
/* NxS[ 197] */ // Shortest string "0."
      new Table(20, 1, -1, new short[] {80}),
/* NxS[ 198] */ // Shortest string ""
      new Table(33, 27, 157, new short[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, 199, 151, 152, 153, 154, 155, 200, 201, 156, 157, 157, 157, 158, 
          157, 157, 157, 157, 159}),
/* NxS[ 199] */ // Shortest string "}"
      new Table(3, 1, -1, new short[] {167}),
/* NxS[ 200] */ // Shortest string "\""
      new Table(9, 1, 200, new short[] {166}),
/* NxS[ 201] */ // Shortest string "'"
      new Table(10, 1, 201, new short[] {166}),
/* NxS[ 202] */ // Shortest string "0."
      new Table(20, 1, -1, new short[] {160}),
    };

int NextState() {
    if (code == ScanBuff.EndOfFile)
        return eofNum;
    else
        unchecked {
            int rslt;
            int idx = MapC(code) - NxS[state].min;
            if (idx < 0) idx += 39;
            if ((uint)idx >= (uint)NxS[state].rng) rslt = NxS[state].dflt;
            else rslt = NxS[state].nxt[idx];
            return rslt;
        }
}

#endregion


#if BACKUP
        // ==============================================================
        // == Nested struct used for backup in automata that do backup ==
        // ==============================================================

        struct Context // class used for automaton backup.
        {
            public int bPos;
            public int rPos; // scanner.readPos saved value
            public int cCol;
            public int lNum; // Need this in case of backup over EOL.
            public int state;
            public int cChr;
        }
        
        private Context ctx = new Context();
#endif // BACKUP

        // ==============================================================
        // ==== Nested struct to support input switching in scanners ====
        // ==============================================================

		struct BufferContext {
            internal ScanBuff buffSv;
			internal int chrSv;
			internal int cColSv;
			internal int lNumSv;
		}

        // ==============================================================
        // ===== Private methods to save and restore buffer contexts ====
        // ==============================================================

        /// <summary>
        /// This method creates a buffer context record from
        /// the current buffer object, together with some
        /// scanner state values. 
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        BufferContext MkBuffCtx()
		{
			BufferContext rslt;
			rslt.buffSv = this.buffer;
			rslt.chrSv = this.code;
			rslt.cColSv = this.cCol;
			rslt.lNumSv = this.lNum;
			return rslt;
		}

        /// <summary>
        /// This method restores the buffer value and allied
        /// scanner state from the given context record value.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void RestoreBuffCtx(BufferContext value)
		{
			this.buffer = value.buffSv;
			this.code = value.chrSv;
			this.cCol = value.cColSv;
			this.lNum = value.lNumSv;
        } 
        // =================== End Nested classes =======================

#if !NOFILES
     public Scanner(Stream file) {
            SetSource(file, 0); // unicode option
        }

        public Scanner(Stream file, string codepage) {
            SetSource(file, CodePageHandling.GetCodePage(codepage));
        }   
#endif // !NOFILES

     public Scanner() { }

        private int readPos;

        void GetCode()
        {
            if (code == '\n')  // This needs to be fixed for other conventions
                               // i.e. [\r\n\205\u2028\u2029]
            { 
                cCol = -1;
                lNum++;
            }
            readPos = buffer.Pos;

            // Now read new codepoint.
            code = buffer.Read();
            if (code > ScanBuff.EndOfFile)
            {
#if (!BYTEMODE)
                if (code >= 0xD800 && code <= 0xDBFF)
                {
                    int next = buffer.Read();
                    if (next < 0xDC00 || next > 0xDFFF)
                        code = ScanBuff.UnicodeReplacementChar;
                    else
                        code = (0x10000 + ((code & 0x3FF) << 10) + (next & 0x3FF));
                }
#endif
                cCol++;
            }
        }

        void MarkToken()
        {
#if (!PERSIST)
            buffer.Mark();
#endif
            tokPos = readPos;
            tokLin = lNum;
            tokCol = cCol;
        }
        
        void MarkEnd()
        {
            tokTxt = null;
            tokEPos = readPos;
            tokELin = lNum;
            tokECol = cCol;
        }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int Peek()
        {
            int rslt, codeSv = code, cColSv = cCol, lNumSv = lNum, bPosSv = buffer.Pos;
            GetCode(); rslt = code;
            lNum = lNumSv; cCol = cColSv; code = codeSv; buffer.Pos = bPosSv;
            return rslt;
        }

        // ==============================================================
        // =====    Initialization of string-based input buffers     ====
        // ==============================================================

        /// <summary>
        /// Create and initialize a StringBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the input string</param>
        /// <param name="offset">starting offset in the string</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(string source, int offset)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.buffer.Pos = offset;
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }

        // ================ LineBuffer Initialization ===================
        /// <summary>
        /// Create and initialize a LineBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the list of input strings</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(IList<string> source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            this.lNum = 0;
            GetCode();
        }

#if !NOFILES        
        // =============== StreamBuffer Initialization ==================

        /// <summary>
        /// Create and initialize a StreamBuff buffer object for this scanner.
        /// StreamBuff is buffer for 8-bit byte files.
        /// </summary>
        /// <param name="source">the input byte stream</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
        
#if !BYTEMODE
        // ================ TextBuffer Initialization ===================

        /// <summary>
        /// Create and initialize a TextBuff buffer object for this scanner.
        /// TextBuff is a buffer for encoded unicode files.
        /// </summary>
        /// <param name="source">the input text file</param>
        /// <param name="fallbackCodePage">Code page to use if file has
        /// no BOM. For 0, use machine default; for -1, 8-bit binary</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source, int fallbackCodePage)
        {
            this.buffer = ScanBuff.GetBuffer(source, fallbackCodePage);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
#endif // !BYTEMODE
#endif // !NOFILES
        
        // ==============================================================

#if BABEL
        //
        //  Get the next token for Visual Studio
        //
        //  "state" is the inout mode variable that maintains scanner
        //  state between calls, using the EolState property. In principle,
        //  if the calls of EolState are costly set could be called once
        //  only per line, at the start; and get called only at the end
        //  of the line. This needs more infrastructure ...
        //
        public int GetNext(ref int state, out int start, out int end)
        {
                Tokens next;
            int s, e;
            s = state;        // state at start
            EolState = state;
                next = (Tokens)Scan();
            state = EolState;
            e = state;       // state at end;
            start = tokPos;
            end = tokEPos - 1; // end is the index of last char.
            return (int)next;
        }        
#endif // BABEL

        // ======== AbstractScanner<> Implementation =========

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public override int yylex()
        {
            // parserMax is set by reflecting on the Tokens
            // enumeration.  If maxParseToken is defined
            // that is used, otherwise int.MaxValue is used.
            int next;
            do { next = Scan(); } while (next >= parserMax);
            return next;
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yypos { get { return tokPos; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yyline { get { return tokLin; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yycol { get { return tokCol; } }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yytext")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yytext")]
        public string yytext
        {
            get 
            {
                if (tokTxt == null) 
                    tokTxt = buffer.GetString(tokPos, tokEPos);
                return tokTxt;
            }
        }

        /// <summary>
        /// Discards all but the first "n" codepoints in the recognized pattern.
        /// Resets the buffer position so that only n codepoints have been consumed;
        /// yytext is also re-evaluated. 
        /// </summary>
        /// <param name="n">The number of codepoints to consume</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void yyless(int n)
        {
            buffer.Pos = tokPos;
            // Must read at least one char, so set before start.
            cCol = tokCol - 1; 
            GetCode();
            // Now ensure that line counting is correct.
            lNum = tokLin;
            // And count the rest of the text.
            for (int i = 0; i < n; i++) GetCode();
            MarkEnd();
        }
       
        //
        //  It would be nice to count backward in the text
        //  but it does not seem possible to re-establish
        //  the correct column counts except by going forward.
        //
        /// <summary>
        /// Removes the last "n" code points from the pattern.
        /// </summary>
        /// <param name="n">The number to remove</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void _yytrunc(int n) { yyless(yyleng - n); }
        
        //
        // This is painful, but we no longer count
        // codepoints.  For the overwhelming majority 
        // of cases the single line code is fast, for
        // the others, well, at least it is all in the
        // buffer so no files are touched. Note that we
        // can't use (tokEPos - tokPos) because of the
        // possibility of surrogate pairs in the token.
        //
        /// <summary>
        /// The length of the pattern in codepoints (not the same as 
        /// string-length if the pattern contains any surrogate pairs).
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yyleng")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yyleng")]
        public int yyleng
        {
            get {
                if (tokELin == tokLin)
                    return tokECol - tokCol;
                else
#if BYTEMODE
                    return tokEPos - tokPos;
#else
                {
                    int ch;
                    int count = 0;
                    int save = buffer.Pos;
                    buffer.Pos = tokPos;
                    do {
                        ch = buffer.Read();
                        if (!char.IsHighSurrogate((char)ch)) count++;
                    } while (buffer.Pos < tokEPos && ch != ScanBuff.EndOfFile);
                    buffer.Pos = save;
                    return count;
                }
#endif // BYTEMODE
            }
        }
        
        // ============ methods available in actions ==============

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int YY_START {
            get { return currentScOrd; }
            set { currentScOrd = value; 
                  currentStart = startState[value]; 
            } 
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void BEGIN(int next) {
            currentScOrd = next;
            currentStart = startState[next];
        }

        // ============== The main tokenizer code =================

        int Scan()
        {
                for (; ; )
                {
                    int next;              // next state to enter                   
#if BACKUP
                    Result rslt = Result.noMatch;
#endif // BACKUP
#if LEFTANCHORS
                    for (;;)
                    {
                        // Discard characters that do not start any pattern.
                        // Must check the left anchor condition after *every* GetCode!
                        state = ((cCol == 0) ? anchorState[currentScOrd] : currentStart);
                        if ((next = NextState()) != goStart) 
                            break; // LOOP EXIT HERE...
                        GetCode();
                    }
                    
#else // !LEFTANCHORS
                    state = currentStart;
                    while ((next = NextState()) == goStart)
                        // At this point, the current character has no
                        // transition from the current state.  We discard 
                        // the "no-match" char.   In traditional LEX such 
                        // characters are echoed to the console.
                        GetCode();
#endif // LEFTANCHORS                    
                    // At last, a valid transition ...    
                    MarkToken();
                    state = next;
                    GetCode();
                    
                    while ((next = NextState()) > eofNum) // Exit for goStart AND for eofNum
#if BACKUP
                        if (state <= maxAccept && next > maxAccept) // need to prepare backup data
                        {
                            // ctx is an object. The fields may be 
                            // mutated by the call to Recurse2.
                            // On return the data in ctx is the
                            // *latest* accept state that was found.
                            
                            rslt = Recurse2(ref ctx, next);
                            if (rslt == Result.noMatch) 
                                RestoreStateAndPos(ref ctx);
                            break;
                        }
                        else
#endif // BACKUP
                        {
                            state = next;
                            GetCode();
                        }
                    if (state <= maxAccept) 
                    {
                        MarkEnd();
#region ActionSwitch
#pragma warning disable 162, 1522
    switch (state)
    {
        case eofNum:
            if (yywrap())
                return (int)Tokens.EOF;
            break;
        case 1: // Recognized '{AnyTextUpToTagOrOutputStart}',	Shortest string ""
        case 2: // Recognized '{AnyTextUpToTagOrOutputStart}',	Shortest string "%"
        case 3: // Recognized '{AnyTextUpToTagOrOutputStart}',	Shortest string ""
yylval.String = yytext; return (int) Tokens.PLAIN;
            break;
        case 4: // Recognized '{OutputStart}',	Shortest string ""
yy_push_state(INOUTPUT); return (int) Tokens.OUTPUT_START;
            break;
        case 5: // Recognized '{TagStart}',	Shortest string ""
BEGIN(INTAG); return (int) Tokens.TAG_START;
            break;
        case 6: // In <CMMT> Recognized '{AnyTextUpToTagStart}',	Shortest string ""
        case 7: // In <CMMT> Recognized '{AnyTextUpToTagStart}',	Shortest string "%"
        case 8: // In <CMMT> Recognized '{AnyTextUpToTagStart}',	Shortest string ""
;
            break;
        case 9: // In <CMMT> Recognized '{TagStart}',	Shortest string ""
BEGIN(CMMT2);
            break;
        case 10: // In <CMMT2> Recognized '{WhiteSpace}',	Shortest string "\t"
;
            break;
        case 11: // In <CMMT2> Recognized '{ENDCOMMENT}',	Shortest string "endcomment"
BEGIN(INTAG); return (int) Tokens.COMMENT;
            break;
        case 12: // In <RAW> Recognized '{WhiteSpace}',	Shortest string "\t"
;
            break;
        case 13: // In <RAW> Recognized '{TagEnd}',	Shortest string "%}"
BEGIN(RAW2);
            break;
        case 14: // In <RAW2> Recognized '{AnyTextUpToTagStart}',	Shortest string ""
        case 15: // In <RAW2> Recognized '{AnyTextUpToTagStart}',	Shortest string "%"
        case 16: // In <RAW2> Recognized '{AnyTextUpToTagStart}',	Shortest string ""
yylval.String = yytext; return (int)Tokens.PLAIN;
            break;
        case 17: // In <RAW2> Recognized '{TagStart}',	Shortest string ""
BEGIN(RAW3);
            break;
        case 18: // In <RAW3> Recognized '{OptionalWhiteSpace}',	Shortest string ""
yylval.String = "<%"+yytext; BEGIN(RAW2); return (int)Tokens.PLAIN;
            break;
        case 19: // In <RAW3> Recognized '{OptionalWhiteSpace}{ENDRAW}',	Shortest string "endraw"
BEGIN(INTAG); return (int)Tokens.END_RAW;
            break;
        case 20: // In <INTAG> Recognized '{WhiteSpace}+',	Shortest string "\t"
;
            break;
        case 21: // In <INTAG> Recognized '{Col}',	Shortest string ":"
return (int) Tokens.COL;
            break;
        case 22: // In <INTAG> Recognized '{Comma}',	Shortest string ","
return (int) Tokens.COMMA;
            break;
        case 23: // In <INTAG> Recognized '{Dot}',	Shortest string "."
return (int) Tokens.DOT;
            break;
        case 24: // In <INTAG> Recognized '{Identifier}',	Shortest string "t"
        case 25: // In <INTAG> Recognized '{Identifier}',	Shortest string "r"
        case 26: // In <INTAG> Recognized '{Identifier}',	Shortest string "u"
        case 27: // In <INTAG> Recognized '{Identifier}',	Shortest string "e"
        case 28: // In <INTAG> Recognized '{Identifier}',	Shortest string "f"
        case 29: // In <INTAG> Recognized '{Identifier}',	Shortest string "a"
        case 30: // In <INTAG> Recognized '{Identifier}',	Shortest string "l"
        case 32: // In <INTAG> Recognized '{Identifier}',	Shortest string "c"
        case 33: // In <INTAG> Recognized '{Identifier}',	Shortest string "o"
        case 34: // In <INTAG> Recognized '{Identifier}',	Shortest string "n"
        case 35: // In <INTAG> Recognized '{Identifier}',	Shortest string "w"
        case 36: // In <INTAG> Recognized '{Identifier}',	Shortest string "i"
        case 48: // In <INTAG> Recognized '{Identifier}',	Shortest string "inc"
        case 49: // In <INTAG> Recognized '{Identifier}',	Shortest string "incl"
        case 50: // In <INTAG> Recognized '{Identifier}',	Shortest string "inclu"
        case 51: // In <INTAG> Recognized '{Identifier}',	Shortest string "includ"
        case 53: // In <INTAG> Recognized '{Identifier}',	Shortest string "wi"
        case 54: // In <INTAG> Recognized '{Identifier}',	Shortest string "wh"
        case 55: // In <INTAG> Recognized '{Identifier}',	Shortest string "whe"
        case 57: // In <INTAG> Recognized '{Identifier}',	Shortest string "wit"
        case 59: // In <INTAG> Recognized '{Identifier}',	Shortest string "ni"
        case 62: // In <INTAG> Recognized '{Identifier}',	Shortest string "ca"
        case 63: // In <INTAG> Recognized '{Identifier}',	Shortest string "co"
        case 64: // In <INTAG> Recognized '{Identifier}',	Shortest string "cy"
        case 65: // In <INTAG> Recognized '{Identifier}',	Shortest string "cyc"
        case 66: // In <INTAG> Recognized '{Identifier}',	Shortest string "cycl"
        case 68: // In <INTAG> Recognized '{Identifier}',	Shortest string "com"
        case 69: // In <INTAG> Recognized '{Identifier}',	Shortest string "comm"
        case 70: // In <INTAG> Recognized '{Identifier}',	Shortest string "comme"
        case 71: // In <INTAG> Recognized '{Identifier}',	Shortest string "commen"
        case 73: // In <INTAG> Recognized '{Identifier}',	Shortest string "cas"
        case 74: // In <INTAG> Recognized '{Identifier}',	Shortest string "cap"
        case 75: // In <INTAG> Recognized '{Identifier}',	Shortest string "capt"
        case 76: // In <INTAG> Recognized '{Identifier}',	Shortest string "captu"
        case 77: // In <INTAG> Recognized '{Identifier}',	Shortest string "captur"
        case 81: // In <INTAG> Recognized '{Identifier}',	Shortest string "as"
        case 82: // In <INTAG> Recognized '{Identifier}',	Shortest string "an"
        case 84: // In <INTAG> Recognized '{Identifier}',	Shortest string "ass"
        case 85: // In <INTAG> Recognized '{Identifier}',	Shortest string "assi"
        case 86: // In <INTAG> Recognized '{Identifier}',	Shortest string "assig"
        case 88: // In <INTAG> Recognized '{Identifier}',	Shortest string "fa"
        case 89: // In <INTAG> Recognized '{Identifier}',	Shortest string "fo"
        case 91: // In <INTAG> Recognized '{Identifier}',	Shortest string "fal"
        case 92: // In <INTAG> Recognized '{Identifier}',	Shortest string "tru"
        case 94: // In <INTAG> Recognized '{Identifier}',	Shortest string "el"
        case 95: // In <INTAG> Recognized '{Identifier}',	Shortest string "en"
        case 96: // In <INTAG> Recognized '{Identifier}',	Shortest string "end"
        case 97: // In <INTAG> Recognized '{Identifier}',	Shortest string "endt"
        case 98: // In <INTAG> Recognized '{Identifier}',	Shortest string "endu"
        case 99: // In <INTAG> Recognized '{Identifier}',	Shortest string "endf"
        case 100: // In <INTAG> Recognized '{Identifier}',	Shortest string "endc"
        case 101: // In <INTAG> Recognized '{Identifier}',	Shortest string "endi"
        case 103: // In <INTAG> Recognized '{Identifier}',	Shortest string "endca"
        case 104: // In <INTAG> Recognized '{Identifier}',	Shortest string "endcas"
        case 105: // In <INTAG> Recognized '{Identifier}',	Shortest string "endcap"
        case 106: // In <INTAG> Recognized '{Identifier}',	Shortest string "endcapt"
        case 107: // In <INTAG> Recognized '{Identifier}',	Shortest string "endcaptu"
        case 108: // In <INTAG> Recognized '{Identifier}',	Shortest string "endcaptur"
        case 111: // In <INTAG> Recognized '{Identifier}',	Shortest string "endfo"
        case 113: // In <INTAG> Recognized '{Identifier}',	Shortest string "endun"
        case 114: // In <INTAG> Recognized '{Identifier}',	Shortest string "endunl"
        case 115: // In <INTAG> Recognized '{Identifier}',	Shortest string "endunle"
        case 116: // In <INTAG> Recognized '{Identifier}',	Shortest string "endunles"
        case 118: // In <INTAG> Recognized '{Identifier}',	Shortest string "endta"
        case 119: // In <INTAG> Recognized '{Identifier}',	Shortest string "endtab"
        case 120: // In <INTAG> Recognized '{Identifier}',	Shortest string "endtabl"
        case 121: // In <INTAG> Recognized '{Identifier}',	Shortest string "endtable"
        case 122: // In <INTAG> Recognized '{Identifier}',	Shortest string "endtabler"
        case 123: // In <INTAG> Recognized '{Identifier}',	Shortest string "endtablero"
        case 125: // In <INTAG> Recognized '{Identifier}',	Shortest string "els"
        case 127: // In <INTAG> Recognized '{Identifier}',	Shortest string "un"
        case 128: // In <INTAG> Recognized '{Identifier}',	Shortest string "unl"
        case 129: // In <INTAG> Recognized '{Identifier}',	Shortest string "unle"
        case 130: // In <INTAG> Recognized '{Identifier}',	Shortest string "unles"
        case 132: // In <INTAG> Recognized '{Identifier}',	Shortest string "ra"
        case 134: // In <INTAG> Recognized '{Identifier}',	Shortest string "tr"
        case 135: // In <INTAG> Recognized '{Identifier}',	Shortest string "ta"
        case 136: // In <INTAG> Recognized '{Identifier}',	Shortest string "ti"
        case 137: // In <INTAG> Recognized '{Identifier}',	Shortest string "tim"
        case 138: // In <INTAG> Recognized '{Identifier}',	Shortest string "time"
        case 139: // In <INTAG> Recognized '{Identifier}',	Shortest string "timeo"
        case 140: // In <INTAG> Recognized '{Identifier}',	Shortest string "timeou"
        case 142: // In <INTAG> Recognized '{Identifier}',	Shortest string "tab"
        case 143: // In <INTAG> Recognized '{Identifier}',	Shortest string "tabl"
        case 144: // In <INTAG> Recognized '{Identifier}',	Shortest string "table"
        case 145: // In <INTAG> Recognized '{Identifier}',	Shortest string "tabler"
        case 146: // In <INTAG> Recognized '{Identifier}',	Shortest string "tablero"
yylval.String = yytext;
					   return (int) Tokens.IDENTIFIER;
            break;
        case 31: // In <INTAG> Recognized '{Num}',	Shortest string "0"
        case 80: // In <INTAG> Recognized '{Num}',	Shortest string "0.0"
double.TryParse (yytext, NumberStyles.Float, CultureInfo.CurrentCulture, out yylval.Double); 
					   return (int) Tokens.NUM_LITERAL;
            break;
        case 37: // In <INTAG> Recognized '{EqSign}',	Shortest string "="
return (int) Tokens.OP_ASSIGN;
            break;
        case 38: // In <INTAG> Recognized '{Gt}',	Shortest string ">"
return (int) Tokens.OP_GT;
            break;
        case 39: // In <INTAG> Recognized '{Lt}',	Shortest string "<"
return (int) Tokens.OP_LT;
            break;
        case 40: // In <INTAG> Recognized '{OPar}',	Shortest string "("
return (int) Tokens.LEFT_PAR;
            break;
        case 41: // In <INTAG> Recognized '{CPar}',	Shortest string ")"
return (int) Tokens.RIGHT_PAR;
            break;
        case 42: // In <INTAG> Recognized '{LtEq}',	Shortest string "<="
return (int) Tokens.OP_LE;
            break;
        case 43: // In <INTAG> Recognized '{GtEq}',	Shortest string ">="
return (int) Tokens.OP_GE;
            break;
        case 44: // In <INTAG> Recognized '{Eq}',	Shortest string "=="
return (int) Tokens.OP_EQ;
            break;
        case 45: // In <INTAG> Recognized '{NEq}',	Shortest string "!="
return (int) Tokens.OP_NE;
            break;
        case 46: // In <INTAG> Recognized '{IF}',	Shortest string "if"
return (int) Tokens.IF;
            break;
        case 47: // In <INTAG> Recognized '{IN}',	Shortest string "in"
return (int) Tokens.IN;
            break;
        case 52: // In <INTAG> Recognized '{INCLUDE}',	Shortest string "include"
return (int) Tokens.INCLUDE;
            break;
        case 56: // In <INTAG> Recognized '{WHEN}',	Shortest string "when"
return (int) Tokens.WHEN;
            break;
        case 58: // In <INTAG> Recognized '{WITH}',	Shortest string "with"
return (int) Tokens.WITH;
            break;
        case 60: // In <INTAG> Recognized '{NIL}',	Shortest string "nil"
return (int) Tokens.NIL_LITERAL;
            break;
        case 61: // In <INTAG> Recognized '{OR}',	Shortest string "or"
return (int) Tokens.OR;
            break;
        case 67: // In <INTAG> Recognized '{CYCLE}',	Shortest string "cycle"
return (int) Tokens.CYCLE;
            break;
        case 72: // In <INTAG> Recognized '{COMMENT}',	Shortest string "comment"
BEGIN(CMMT);
            break;
        case 78: // In <INTAG> Recognized '{CAPTURE}',	Shortest string "capture"
return (int) Tokens.CAPTURE;
            break;
        case 79: // In <INTAG> Recognized '{CASE}',	Shortest string "case"
return (int) Tokens.CASE;
            break;
        case 83: // In <INTAG> Recognized '{AND}',	Shortest string "and"
return (int) Tokens.AND;
            break;
        case 87: // In <INTAG> Recognized '{ASSIGN}',	Shortest string "assign"
return (int) Tokens.ASSIGN;
            break;
        case 90: // In <INTAG> Recognized '{FOR}',	Shortest string "for"
return (int) Tokens.FOR;
            break;
        case 93: // In <INTAG> Recognized '{BooleanLiteral}',	Shortest string "true"
bool.TryParse(yytext, out yylval.Bool);
 					   return (int) Tokens.BOOL_LITERAL;
            break;
        case 102: // In <INTAG> Recognized '{ENDIF}',	Shortest string "endif"
return (int) Tokens.END_IF;
            break;
        case 109: // In <INTAG> Recognized '{ENDCAPTURE}',	Shortest string "endcapture"
return (int) Tokens.END_CAPTURE;
            break;
        case 110: // In <INTAG> Recognized '{ENDCASE}',	Shortest string "endcase"
return (int) Tokens.END_CASE;
            break;
        case 112: // In <INTAG> Recognized '{ENDFOR}',	Shortest string "endfor"
return (int) Tokens.END_FOR;
            break;
        case 117: // In <INTAG> Recognized '{ENDUNLESS}',	Shortest string "endunless"
return (int) Tokens.END_UNLESS;
            break;
        case 124: // In <INTAG> Recognized '{ENDTABLEROW}',	Shortest string "endtablerow"
return (int) Tokens.END_TABLE;
            break;
        case 126: // In <INTAG> Recognized '{ELSE}',	Shortest string "else"
return (int) Tokens.ELSE;
            break;
        case 131: // In <INTAG> Recognized '{UNLESS}',	Shortest string "unless"
return (int) Tokens.UNLESS;
            break;
        case 133: // In <INTAG> Recognized '{RAW}',	Shortest string "raw"
BEGIN(RAW); return (int) Tokens.END_RAW;
            break;
        case 141: // In <INTAG> Recognized '{TIMEOUT}',	Shortest string "timeout"
return (int) Tokens.TIMEOUT;
            break;
        case 147: // In <INTAG> Recognized '{TABLEROW}',	Shortest string "tablerow"
return (int) Tokens.TABLE;
            break;
        case 148: // In <INTAG> Recognized '{Str}',	Shortest string "\"\""
if (yytext.Length > 2) 
 					       yylval.String = yytext.Substring(1, yytext.Length - 2);
 					   else
 					       yylval.String = ""; 
 					   return (int) Tokens.STRING_LITERAL;
            break;
        case 149: // In <INTAG> Recognized '{DotDot}',	Shortest string ".."
return (int) Tokens.DOT_DOT;
            break;
        case 150: // In <INTAG> Recognized '{TagEnd}',	Shortest string "%}"
BEGIN(INITIAL); return (int) Tokens.TAG_END;
            break;
        case 151: // In <INOUTPUT> Recognized '{WhiteSpace}+',	Shortest string "\t"
;
            break;
        case 152: // In <INOUTPUT> Recognized '{Pipe}',	Shortest string "|"
return (int) Tokens.PIPE;
            break;
        case 153: // In <INOUTPUT> Recognized '{Col}',	Shortest string ":"
return (int) Tokens.COL;
            break;
        case 154: // In <INOUTPUT> Recognized '{Comma}',	Shortest string ","
return (int) Tokens.COMMA;
            break;
        case 155: // In <INOUTPUT> Recognized '{Dot}',	Shortest string "."
return (int) Tokens.DOT;
            break;
        case 156: // In <INOUTPUT> Recognized '{Identifier}',	Shortest string "t"
        case 157: // In <INOUTPUT> Recognized '{Identifier}',	Shortest string "r"
        case 158: // In <INOUTPUT> Recognized '{Identifier}',	Shortest string "f"
        case 161: // In <INOUTPUT> Recognized '{Identifier}',	Shortest string "fa"
        case 162: // In <INOUTPUT> Recognized '{Identifier}',	Shortest string "fal"
        case 163: // In <INOUTPUT> Recognized '{Identifier}',	Shortest string "tru"
        case 165: // In <INOUTPUT> Recognized '{Identifier}',	Shortest string "tr"
yylval.String = yytext;
					   return (int) Tokens.IDENTIFIER;
            break;
        case 159: // In <INOUTPUT> Recognized '{Num}',	Shortest string "0"
        case 160: // In <INOUTPUT> Recognized '{Num}',	Shortest string "0.0"
double.TryParse (yytext, NumberStyles.Float, CultureInfo.CurrentCulture, out yylval.Double); 
					   return (int) Tokens.NUM_LITERAL;
            break;
        case 164: // In <INOUTPUT> Recognized '{BooleanLiteral}',	Shortest string "true"
bool.TryParse(yytext, out yylval.Bool);
 					   return (int) Tokens.BOOL_LITERAL;
            break;
        case 166: // In <INOUTPUT> Recognized '{Str}',	Shortest string "\"\""
if (yytext.Length > 2) 
 					       yylval.String = yytext.Substring(1, yytext.Length - 2);
 					   else
 					       yylval.String = ""; 
 					   return (int) Tokens.STRING_LITERAL;
            break;
        case 167: // In <INOUTPUT> Recognized '{OutputEnd}',	Shortest string "}}"
yy_pop_state(); return (int) Tokens.OUTPUT_END;
            break;
        default:
            break;
    }
#pragma warning restore 162, 1522
#endregion
                    }
                }
        }

#if BACKUP
        Result Recurse2(ref Context ctx, int next)
        {
            // Assert: at entry "state" is an accept state AND
            //         NextState(state, code) != goStart AND
            //         NextState(state, code) is not an accept state.
            //
            SaveStateAndPos(ref ctx);
            state = next;
            GetCode();

            while ((next = NextState()) > eofNum)
            {
                if (state <= maxAccept && next > maxAccept) // need to update backup data
                    SaveStateAndPos(ref ctx);
                state = next;
                if (state == eofNum) return Result.accept;
                GetCode(); 
            }
            return (state <= maxAccept ? Result.accept : Result.noMatch);
        }

        void SaveStateAndPos(ref Context ctx)
        {
            ctx.bPos  = buffer.Pos;
            ctx.rPos  = readPos;
            ctx.cCol  = cCol;
            ctx.lNum  = lNum;
            ctx.state = state;
            ctx.cChr  = code;
        }

        void RestoreStateAndPos(ref Context ctx)
        {
            buffer.Pos = ctx.bPos;
            readPos = ctx.rPos;
            cCol  = ctx.cCol;
            lNum  = ctx.lNum;
            state = ctx.state;
            code  = ctx.cChr;
        }

#endif // BACKUP

        // ============= End of the tokenizer code ================

#if STACK        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void yy_clear_stack() { scStack.Clear(); }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int yy_top_state() { return scStack.Peek(); }
        
        internal void yy_push_state(int state)
        {
            scStack.Push(currentScOrd);
            BEGIN(state);
        }
        
        internal void yy_pop_state()
        {
            // Protect against input errors that pop too far ...
            if (scStack.Count > 0) {
				int newSc = scStack.Pop();
				BEGIN(newSc);
            } // Otherwise leave stack unchanged.
        }
 #endif // STACK

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void ECHO() { Console.Out.Write(yytext); }
        
    } // end class $Scanner

// ==============================================================
// <auto-generated>
// This code automatically produced from an embedded resource.
// Do not edit this file, or it will become incompatible with 
// the specification from which it was generated.
// </auto-generated>
// ==============================================================

// Code copied from GPLEX embedded resource
    [Serializable]
    public class BufferException : Exception
    {
        public BufferException() { }
        public BufferException(string message) : base(message) { }
        public BufferException(string message, Exception innerException)
            : base(message, innerException) { }
        protected BufferException(SerializationInfo info, StreamingContext context)
            : base(info, context) { }
    }

    public abstract class ScanBuff
    {
        private string fileNm;

        public const int EndOfFile = -1;
        public const int UnicodeReplacementChar = 0xFFFD;

        public bool IsFile { get { return (fileNm != null); } }
        public string FileName { get { return fileNm; } set { fileNm = value; } }

        public abstract int Pos { get; set; }
        public abstract int Read();
        public virtual void Mark() { }

        public abstract string GetString(int begin, int limit);

        public static ScanBuff GetBuffer(string source)
        {
            return new StringBuffer(source);
        }

        public static ScanBuff GetBuffer(IList<string> source)
        {
            return new LineBuffer(source);
        }

#if (!NOFILES)
        public static ScanBuff GetBuffer(Stream source)
        {
            return new BuildBuffer(source);
        }

#if (!BYTEMODE)
        public static ScanBuff GetBuffer(Stream source, int fallbackCodePage)
        {
            return new BuildBuffer(source, fallbackCodePage);
        }
#endif // !BYTEMODE
#endif // !NOFILES
    }

    #region Buffer classes

    // ==============================================================
    // =====  Definitions for various ScanBuff derived classes   ====
    // ==============================================================
    // ===============         String input          ================
    // ==============================================================

    /// <summary>
    /// This class reads characters from a single string as
    /// required, for example, by Visual Studio language services
    /// </summary>
    sealed class StringBuffer : ScanBuff
    {
        string str;        // input buffer
        int bPos;          // current position in buffer
        int sLen;

        public StringBuffer(string source)
        {
            this.str = source;
            this.sLen = source.Length;
            this.FileName = null;
        }

        public override int Read()
        {
            if (bPos < sLen) return str[bPos++];
            else if (bPos == sLen) { bPos++; return '\n'; }   // one strike, see new line
            else { bPos++; return EndOfFile; }                // two strikes and you're out!
        }

        public override string GetString(int begin, int limit)
        {
            //  "limit" can be greater than sLen with the BABEL
            //  option set.  Read returns a "virtual" EOL if
            //  an attempt is made to read past the end of the
            //  string buffer.  Without the guard any attempt 
            //  to fetch yytext for a token that includes the 
            //  EOL will throw an index exception.
            if (limit > sLen) limit = sLen;
            if (limit <= begin) return "";
            else return str.Substring(begin, limit - begin);
        }

        public override int Pos
        {
            get { return bPos; }
            set { bPos = value; }
        }

        public override string ToString() { return "StringBuffer"; }
    }

    // ==============================================================
    //  The LineBuff class contributed by Nigel Horspool, 
    //  nigelh@cs.uvic.cs
    // ==============================================================

    sealed class LineBuffer : ScanBuff
    {
        IList<string> line;    // list of source lines from a file
        int numLines;          // number of strings in line list
        string curLine;        // current line in that list
        int cLine;             // index of current line in the list
        int curLen;            // length of current line
        int curLineStart;      // position of line start in whole file
        int curLineEnd;        // position of line end in whole file
        int maxPos;            // max position ever visited in whole file
        int cPos;              // ordinal number of code in source

        // Constructed from a list of strings, one per source line.
        // The lines have had trailing '\n' characters removed.
        public LineBuffer(IList<string> lineList)
        {
            line = lineList;
            numLines = line.Count;
            cPos = curLineStart = 0;
            curLine = (numLines > 0 ? line[0] : "");
            maxPos = curLineEnd = curLen = curLine.Length;
            cLine = 1;
            FileName = null;
        }

        public override int Read()
        {
            if (cPos < curLineEnd)
                return curLine[cPos++ - curLineStart];
            if (cPos++ == curLineEnd)
                return '\n';
            if (cLine >= numLines)
                return EndOfFile;
            curLine = line[cLine];
            curLen = curLine.Length;
            curLineStart = curLineEnd + 1;
            curLineEnd = curLineStart + curLen;
            if (curLineEnd > maxPos)
                maxPos = curLineEnd;
            cLine++;
            return curLen > 0 ? curLine[0] : '\n';
        }

        // To speed up searches for the line containing a position
        private int cachedPosition;
        private int cachedIxdex;
        private int cachedLineStart;

        // Given a position pos within the entire source, the results are
        //   ix     -- the index of the containing line
        //   lstart -- the position of the first character on that line
        private void findIndex(int pos, out int ix, out int lstart)
        {
            if (pos >= cachedPosition)
            {
                ix = cachedIxdex; lstart = cachedLineStart;
            }
            else
            {
                ix = lstart = 0;
            }
            while (ix < numLines)
            {
                int len = line[ix].Length + 1;
                if (pos < lstart + len) break;
                lstart += len;
                ix++;
            }
            cachedPosition = pos;
            cachedIxdex = ix;
            cachedLineStart = lstart;
        }

        public override string GetString(int begin, int limit)
        {
            if (begin >= maxPos || limit <= begin) return "";
            int endIx, begIx, endLineStart, begLineStart;
            findIndex(begin, out begIx, out begLineStart);
            int begCol = begin - begLineStart;
            findIndex(limit, out endIx, out endLineStart);
            int endCol = limit - endLineStart;
            string s = line[begIx];
            if (begIx == endIx)
            {
                // the usual case, substring all on one line
                return (endCol <= s.Length) ?
                    s.Substring(begCol, endCol - begCol)
                    : s.Substring(begCol) + "\n";
            }
            // the string spans multiple lines, yuk!
            StringBuilder sb = new StringBuilder();
            if (begCol < s.Length)
                sb.Append(s.Substring(begCol));
            for (; ; )
            {
                sb.Append("\n");
                s = line[++begIx];
                if (begIx >= endIx) break;
                sb.Append(s);
            }
            if (endCol <= s.Length)
            {
                sb.Append(s.Substring(0, endCol));
            }
            else
            {
                sb.Append(s);
                sb.Append("\n");
            }
            return sb.ToString();
        }

        public override int Pos
        {
            get { return cPos; }
            set
            {
                cPos = value;
                findIndex(cPos, out cLine, out curLineStart);
                // cLine should be the *next* line after curLine.
                curLine = (cLine < numLines ? line[cLine++] : "");
                curLineEnd = curLineStart + curLine.Length;
            }
        }

        public override string ToString() { return "LineBuffer"; }
    }

#if (!NOFILES)
    // ==============================================================
    // =====     class BuildBuff : for unicode text files    ========
    // ==============================================================

    class BuildBuffer : ScanBuff
    {
        // Double buffer for char stream.
        class BufferElement
        {
            StringBuilder bldr = new StringBuilder();
            StringBuilder next = new StringBuilder();
            int minIx;
            int maxIx;
            int brkIx;
            bool appendToNext;

            internal BufferElement() { }

            internal int MaxIndex { get { return maxIx; } }
            // internal int MinIndex { get { return minIx; } }

            internal char this[int index]
            {
                get
                {
                    if (index < minIx || index >= maxIx)
                        throw new BufferException("Index was outside data buffer");
                    else if (index < brkIx)
                        return bldr[index - minIx];
                    else
                        return next[index - brkIx];
                }
            }

            internal void Append(char[] block, int count)
            {
                maxIx += count;
                if (appendToNext)
                    this.next.Append(block, 0, count);
                else
                {
                    this.bldr.Append(block, 0, count);
                    brkIx = maxIx;
                    appendToNext = true;
                }
            }

            internal string GetString(int start, int limit)
            {
                if (limit <= start)
                    return "";
                if (start >= minIx && limit <= maxIx)
                    if (limit < brkIx) // String entirely in bldr builder
                        return bldr.ToString(start - minIx, limit - start);
                    else if (start >= brkIx) // String entirely in next builder
                        return next.ToString(start - brkIx, limit - start);
                    else // Must do a string-concatenation
                        return
                            bldr.ToString(start - minIx, brkIx - start) +
                            next.ToString(0, limit - brkIx);
                else
                    throw new BufferException("String was outside data buffer");
            }

            internal void Mark(int limit)
            {
                if (limit > brkIx + 16) // Rotate blocks
                {
                    StringBuilder temp = bldr;
                    bldr = next;
                    next = temp;
                    next.Length = 0;
                    minIx = brkIx;
                    brkIx = maxIx;
                }
            }
        }

        BufferElement data = new BufferElement();

        int bPos;            // Postion index in the StringBuilder
        BlockReader NextBlk; // Delegate that serves char-arrays;

        private string EncodingName
        {
            get
            {
                StreamReader rdr = NextBlk.Target as StreamReader;
                return (rdr == null ? "raw-bytes" : rdr.CurrentEncoding.BodyName);
            }
        }

        public BuildBuffer(Stream stream)
        {
            FileStream fStrm = (stream as FileStream);
            if (fStrm != null) FileName = fStrm.Name;
            NextBlk = BlockReaderFactory.Raw(stream);
        }

#if (!BYTEMODE)
        public BuildBuffer(Stream stream, int fallbackCodePage)
        {
            FileStream fStrm = (stream as FileStream);
            if (fStrm != null) FileName = fStrm.Name;
            NextBlk = BlockReaderFactory.Get(stream, fallbackCodePage);
        }
#endif

        /// <summary>
        /// Marks a conservative lower bound for the buffer,
        /// allowing space to be reclaimed.  If an application 
        /// needs to call GetString at arbitrary past locations 
        /// in the input stream, Mark() is not called.
        /// </summary>
        public override void Mark() { data.Mark(bPos - 2); }

        public override int Pos
        {
            get { return bPos; }
            set { bPos = value; }
        }


        /// <summary>
        /// Read returns the ordinal number of the next char, or 
        /// EOF (-1) for an end of stream.  Note that the next
        /// code point may require *two* calls of Read().
        /// </summary>
        /// <returns></returns>
        public override int Read()
        {
            //
            //  Characters at positions 
            //  [data.offset, data.offset + data.bldr.Length)
            //  are available in data.bldr.
            //
            if (bPos < data.MaxIndex)
            {
                // ch0 cannot be EOF
                return (int)data[bPos++];
            }
            else // Read from underlying stream
            {
                // Experimental code, blocks of page size
                char[] chrs = new char[4096];
                int count = NextBlk(chrs, 0, 4096);
                if (count == 0)
                    return EndOfFile;
                else
                {
                    data.Append(chrs, count);
                    return (int)data[bPos++];
                }
            }
        }

        public override string GetString(int begin, int limit)
        {
            return data.GetString(begin, limit);
        }

        public override string ToString()
        {
            return "StringBuilder buffer, encoding: " + this.EncodingName;
        }
    }

    // =============== End ScanBuff-derived classes ==================

    public delegate int BlockReader(char[] block, int index, int number);

    // A delegate factory, serving up a delegate that
    // reads a block of characters from the underlying
    // encoded stream, via a StreamReader object.
    //
    public static class BlockReaderFactory
    {
        public static BlockReader Raw(Stream stream)
        {
            return delegate(char[] block, int index, int number)
            {
                byte[] b = new byte[number];
                int count = stream.Read(b, 0, number);
                int i = 0;
                int j = index;
                for (; i < count; i++, j++)
                    block[j] = (char)b[i];
                return count;
            };
        }

#if (!BYTEMODE)
        public static BlockReader Get(Stream stream, int fallbackCodePage)
        {
            Encoding encoding;
            int preamble = Preamble(stream);

            if (preamble != 0)  // There is a valid BOM here!
                encoding = Encoding.GetEncoding(preamble);
            else if (fallbackCodePage == -1) // Fallback is "raw" bytes
                return Raw(stream);
            else if (fallbackCodePage != -2) // Anything but "guess"
                encoding = Encoding.GetEncoding(fallbackCodePage);
            else // This is the "guess" option
            {
                int guess = new Guesser(stream).GuessCodePage();
                stream.Seek(0, SeekOrigin.Begin);
                if (guess == -1) // ==> this is a 7-bit file
                    encoding = Encoding.ASCII;
                else if (guess == 65001)
                    encoding = Encoding.UTF8;
                else             // ==> use the machine default
                    encoding = Encoding.Default;
            }
            StreamReader reader = new StreamReader(stream, encoding);
            return reader.Read;
        }

        static int Preamble(Stream stream)
        {
            int b0 = stream.ReadByte();
            int b1 = stream.ReadByte();

            if (b0 == 0xfe && b1 == 0xff)
                return 1201; // UTF16BE
            if (b0 == 0xff && b1 == 0xfe)
                return 1200; // UTF16LE

            int b2 = stream.ReadByte();
            if (b0 == 0xef && b1 == 0xbb && b2 == 0xbf)
                return 65001; // UTF8
            //
            // There is no unicode preamble, so we
            // return denoter for the machine default.
            //
            stream.Seek(0, SeekOrigin.Begin);
            return 0;
        }
#endif // !BYTEMODE
    }
#endif // !NOFILES
    #endregion Buffer classes

    // ==============================================================
    // ============      class CodePageHandling         =============
    // ==============================================================
#if (!NOFILES)
    public static class CodePageHandling
    {
        public static int GetCodePage(string option)
        {
            string command = option.ToUpperInvariant();
            if (command.StartsWith("CodePage:", StringComparison.OrdinalIgnoreCase))
                command = command.Substring(9);
            try
            {
                if (command.Equals("RAW"))
                    return -1;
                else if (command.Equals("GUESS"))
                    return -2;
                else if (command.Equals("DEFAULT"))
                    return 0;
                else if (char.IsDigit(command[0]))
                    return int.Parse(command, CultureInfo.InvariantCulture);
                else
                {
                    Encoding enc = Encoding.GetEncoding(command);
                    return enc.CodePage;
                }
            }
            catch (FormatException)
            {
                Console.Error.WriteLine(
                    "Invalid format \"{0}\", using machine default", option);
            }
            catch (ArgumentException)
            {
                Console.Error.WriteLine(
                    "Unknown code page \"{0}\", using machine default", option);
            }
            return 0;
        }
    }
#region guesser
#if (!BYTEMODE)
    // ==============================================================
    // ============          Encoding Guesser           =============
    // ==============================================================

    /// <summary>
    /// This class provides a simple finite state automaton that
    /// scans the file looking for (1) valid UTF-8 byte patterns,
    /// (2) bytes >= 0x80 which are not part of a UTF-8 sequence.
    /// The method then guesses whether it is UTF-8 or maybe some 
    /// local machine default encoding.  This works well for the
    /// various Latin encodings.
    /// </summary>
    internal class Guesser
    {
        ScanBuff buffer;

        public int GuessCodePage() { return Scan(); }

        const int maxAccept = 10;
        const int initial = 0;
        const int eofNum = 0;
        const int goStart = -1;
        const int INITIAL = 0;
        const int EndToken = 0;

        #region user code
        /* 
         *  Reads the bytes of a file to determine if it is 
         *  UTF-8 or a single-byte code page file.
         */
        public long utfX;
        public long uppr;
        #endregion user code

        int state;
        int currentStart = startState[0];
        int code;

        #region ScannerTables
        static int[] startState = new int[] { 11, 0 };

        #region CharacterMap
        static sbyte[] map = new sbyte[256] {
/*     '\0' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*   '\x10' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*   '\x20' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*      '0' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*      '@' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*      'P' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*      '`' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*      'p' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*   '\x80' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/*   '\x90' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/*   '\xA0' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/*   '\xB0' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/*   '\xC0' */ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
/*   '\xD0' */ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
/*   '\xE0' */ 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
/*   '\xF0' */ 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5 };
        #endregion

        static sbyte[][] nextState = new sbyte[][] {
            new sbyte[] {0, 0, 0, 0, 0, 0},
            new sbyte[] {-1, -1, 10, -1, -1, -1},
            new sbyte[] {-1, -1, -1, -1, -1, -1},
            new sbyte[] {-1, -1, 8, -1, -1, -1},
            new sbyte[] {-1, -1, 5, -1, -1, -1},
            new sbyte[] {-1, -1, 6, -1, -1, -1},
            new sbyte[] {-1, -1, 7, -1, -1, -1},
            null,
            new sbyte[] {-1, -1, 9, -1, -1, -1},
            null,
            null,
            new sbyte[] {-1, 1, 2, 3, 4, 2}
        };


        [SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline")]
        // Reason for suppression: cannot have self-reference in array initializer.
        static Guesser()
        {
            nextState[7] = nextState[2];
            nextState[9] = nextState[2];
            nextState[10] = nextState[2];
        }

        int NextState()
        {
            if (code == ScanBuff.EndOfFile)
                return eofNum;
            else
                return nextState[state][map[code]];
        }
        #endregion

        public Guesser(System.IO.Stream file) { SetSource(file); }

        public void SetSource(System.IO.Stream source)
        {
            this.buffer = new BuildBuffer(source);
            code = buffer.Read();
        }

        int Scan()
        {
            for (; ; )
            {
                int next;
                state = currentStart;
                while ((next = NextState()) == goStart)
                    code = buffer.Read();

                state = next;
                code = buffer.Read();

                while ((next = NextState()) > eofNum)
                {
                    state = next;
                    code = buffer.Read();
                }
                if (state <= maxAccept)
                {
                    #region ActionSwitch
#pragma warning disable 162
                    switch (state)
                    {
                        case eofNum:
                            switch (currentStart)
                            {
                                case 11:
                                    if (utfX == 0 && uppr == 0) return -1; /* raw ascii */
                                    else if (uppr * 10 > utfX) return 0;   /* default code page */
                                    else return 65001;                     /* UTF-8 encoding */
                                    break;
                            }
                            return EndToken;
                        case 1: // Recognized '{Upper128}',	Shortest string "\xC0"
                        case 2: // Recognized '{Upper128}',	Shortest string "\x80"
                        case 3: // Recognized '{Upper128}',	Shortest string "\xE0"
                        case 4: // Recognized '{Upper128}',	Shortest string "\xF0"
                            uppr++;
                            break;
                        case 5: // Recognized '{Utf8pfx4}{Utf8cont}',	Shortest string "\xF0\x80"
                            uppr += 2;
                            break;
                        case 6: // Recognized '{Utf8pfx4}{Utf8cont}{2}',	Shortest string "\xF0\x80\x80"
                            uppr += 3;
                            break;
                        case 7: // Recognized '{Utf8pfx4}{Utf8cont}{3}',	Shortest string "\xF0\x80\x80\x80"
                            utfX += 3;
                            break;
                        case 8: // Recognized '{Utf8pfx3}{Utf8cont}',	Shortest string "\xE0\x80"
                            uppr += 2;
                            break;
                        case 9: // Recognized '{Utf8pfx3}{Utf8cont}{2}',	Shortest string "\xE0\x80\x80"
                            utfX += 2;
                            break;
                        case 10: // Recognized '{Utf8pfx2}{Utf8cont}',	Shortest string "\xC0\x80"
                            utfX++;
                            break;
                        default:
                            break;
                    }
#pragma warning restore 162
                    #endregion
                }
            }
        }
    } // end class Guesser
    
#endif // !BYTEMODE
#endregion
#endif // !NOFILES

// End of code copied from embedded resource

} // end namespace
